computed = [  ]
name = "game::systems::game::Game"
reads = [ ]
writes = [ "Account", "Heroes", "Runes", "ArenaAccount", "ArenaConfig", "ArenaCurrentRankIndex", "ArenaTeam", "EnemyRanges", "GemsRewards", "ArenaBattleStorage", "BattleStorage", "EntityStorage", "HealthOnTurnProcStorage", "TurnTimelineStorage", "LevelEnemy", "LevelInfos", "SkillBuff", "SkillInfos", "SkillNameSet", "BaseStatistics", "BonusRuneStatistics", "RuneStatistics" ]
init_calldata = []

