[world]
kind = "WorldContract"
class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
original_class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x43f5a4477cb4fd56a23cf3ccf5172c95bd90caf1ed0813d4989f5e7449d102f"
transaction_hash = "0x77b2239f99f794d02c520910c1aed14f4435aa782056c2cbebf2f2bd219f5d9"
block_number = 3
seed = "game"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x349651054fdd167d9cac22e2dc68f527c1eddcd7823ec779f3ae662eada3dc9"
class_hash = "0x64e26818f2685ab2ac2c59da1bfbb5d45c22bc0c744aa1dcd919008c9edbdfe"
original_class_hash = "0x64e26818f2685ab2ac2c59da1bfbb5d45c22bc0c744aa1dcd919008c9edbdfe"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/game_systems_game_Game.json"
reads = []
writes = [
    "Account",
    "Heroes",
    "Runes",
    "ArenaAccount",
    "ArenaConfig",
    "ArenaCurrentRankIndex",
    "ArenaTeam",
    "EnemyRanges",
    "GemsRewards",
    "ArenaBattleStorage",
    "BattleStorage",
    "EntityStorage",
    "HealthOnTurnProcStorage",
    "TurnTimelineStorage",
    "LevelEnemy",
    "LevelInfos",
    "SkillBuff",
    "SkillInfos",
    "SkillNameSet",
    "BaseStatistics",
    "BonusRuneStatistics",
    "RuneStatistics",
]
computed = []
init_calldata = []
name = "game::systems::game::Game"

[[contracts]]
kind = "DojoContract"
address = "0x1fbf77ab7d4a5ad70e732231d18d4bbaade6f280cc7d37bfc9116b2f29f0bec"
class_hash = "0xb6b0f34d86a5f716353a759ee89be1b15522e539e8579b46f1a90d3ffa991d"
original_class_hash = "0xb6b0f34d86a5f716353a759ee89be1b15522e539e8579b46f1a90d3ffa991d"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/game_systems_settings_Settings.json"
reads = []
writes = [
    "Account",
    "Heroes",
    "Runes",
    "ArenaAccount",
    "ArenaConfig",
    "ArenaCurrentRankIndex",
    "ArenaTeam",
    "EnemyRanges",
    "GemsRewards",
    "ArenaBattleStorage",
    "BattleStorage",
    "EntityStorage",
    "HealthOnTurnProcStorage",
    "TurnTimelineStorage",
    "LevelEnemy",
    "LevelInfos",
    "SkillBuff",
    "SkillInfos",
    "SkillNameSet",
    "BaseStatistics",
    "BonusRuneStatistics",
    "RuneStatistics",
]
computed = []
init_calldata = []
name = "game::systems::settings::Settings"

[[models]]
kind = "DojoModel"
class_hash = "0x708bfcebe814f943681f1353e0d8625fac2fb8a4c85916cbbe98dec694689bd"
original_class_hash = "0x708bfcebe814f943681f1353e0d8625fac2fb8a4c85916cbbe98dec694689bd"
abi = "manifests/dev/abis/deployments/models/game_models_account_account.json"
name = "game::models::account::account"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "username"
type = "felt252"
key = false

[[models.members]]
name = "energy"
type = "u16"
key = false

[[models.members]]
name = "pvpEnergy"
type = "u16"
key = false

[[models.members]]
name = "crystals"
type = "u32"
key = false

[[models.members]]
name = "gems"
type = "u32"
key = false

[[models.members]]
name = "lastEnergyUpdateTimestamp"
type = "u64"
key = false

[[models.members]]
name = "lastPvpEnergyUpdateTimestamp"
type = "u64"
key = false

[[models.members]]
name = "runesCount"
type = "u32"
key = false

[[models.members]]
name = "heroesCount"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4de3376b236b4f775c4f26541befd8c8a615794d12d94cffe22f4b8ab56c3ef"
original_class_hash = "0x4de3376b236b4f775c4f26541befd8c8a615794d12d94cffe22f4b8ab56c3ef"
abi = "manifests/dev/abis/deployments/models/game_models_account_heroes_heroes.json"
name = "game::models::account::heroes::heroes"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "hero"
type = "Hero"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xc277e179f7840eb573bf7bb7722332a39abee1d7bcf77c50a76c1950b1f38d"
original_class_hash = "0xc277e179f7840eb573bf7bb7722332a39abee1d7bcf77c50a76c1950b1f38d"
abi = "manifests/dev/abis/deployments/models/game_models_account_runes_runes.json"
name = "game::models::account::runes::runes"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "rune"
type = "Rune"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57eb5e7ac2ccef594076d5c6d5ec24c1a0fe6feeb23e874d14fdfda5ca147bc"
original_class_hash = "0x57eb5e7ac2ccef594076d5c6d5ec24c1a0fe6feeb23e874d14fdfda5ca147bc"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_arenaAccount_arena_account.json"
name = "game::models::storage::arena::arenaAccount::arena_account"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "rank"
type = "u64"
key = false

[[models.members]]
name = "lastClaimedRewards"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3c14f7fcaa423bfb8e1ee011e049a49e629bf6cc7975a30e3460dd0ab2d4af8"
original_class_hash = "0x3c14f7fcaa423bfb8e1ee011e049a49e629bf6cc7975a30e3460dd0ab2d4af8"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_arenaConfig_arena_config.json"
name = "game::models::storage::arena::arenaConfig::arena_config"

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "enemyRangesByRankLength"
type = "u32"
key = false

[[models.members]]
name = "gemsRewardsLength"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x330daa5ed958ba7d6dc2250fe93ceb87c69be34822458bdc0cf600f68311698"
original_class_hash = "0x330daa5ed958ba7d6dc2250fe93ceb87c69be34822458bdc0cf600f68311698"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_arenaCurrentRankIndex_arena_current_rank_index.json"
name = "game::models::storage::arena::arenaCurrentRankIndex::arena_current_rank_index"

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "currentRankIndex"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6637c18aa2dab2e38e38241ea82877d418607a36ff1318c0f3af62fa0570e34"
original_class_hash = "0x6637c18aa2dab2e38e38241ea82877d418607a36ff1318c0f3af62fa0570e34"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_arenaTeam_arena_team.json"
name = "game::models::storage::arena::arenaTeam::arena_team"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "heroIndex"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x11e210352255a78c18e716d0ba63623dfee294dabd0d01b7f684dd80810da5d"
original_class_hash = "0x11e210352255a78c18e716d0ba63623dfee294dabd0d01b7f684dd80810da5d"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_enemyRanges_enemy_ranges.json"
name = "game::models::storage::arena::enemyRanges::enemy_ranges"

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "minRank"
type = "u64"
key = false

[[models.members]]
name = "range"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x63597f518cc1e47514e2f939b84e1f596f534f4d3f302dbc54c9e13c19a2d05"
original_class_hash = "0x63597f518cc1e47514e2f939b84e1f596f534f4d3f302dbc54c9e13c19a2d05"
abi = "manifests/dev/abis/deployments/models/game_models_storage_arena_gemsRewards_gems_rewards.json"
name = "game::models::storage::arena::gemsRewards::gems_rewards"

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "minRank"
type = "u64"
key = false

[[models.members]]
name = "gems"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42451b80683f8654453cd3774ccefeab261ddc905ddf7fd05d1fd4dd9521a0"
original_class_hash = "0x42451b80683f8654453cd3774ccefeab261ddc905ddf7fd05d1fd4dd9521a0"
abi = "manifests/dev/abis/deployments/models/game_models_storage_battles_arenaBattleStorage_arena_battle_storage.json"
name = "game::models::storage::battles::arenaBattleStorage::arena_battle_storage"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "enemyOwner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x328dfd8578e02faf5d7a0cdb27155070e6a9b6a5c953171d1b1371f58fbce26"
original_class_hash = "0x328dfd8578e02faf5d7a0cdb27155070e6a9b6a5c953171d1b1371f58fbce26"
abi = "manifests/dev/abis/deployments/models/game_models_storage_battles_battleStorage_battle_storage.json"
name = "game::models::storage::battles::battleStorage::battle_storage"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "level"
type = "u16"
key = false

[[models.members]]
name = "entitiesCount"
type = "u32"
key = false

[[models.members]]
name = "aliveEntitiesCount"
type = "u32"
key = false

[[models.members]]
name = "isBattleOver"
type = "bool"
key = false

[[models.members]]
name = "isWaitingForPlayerAction"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x8229c3d9b1c3f36ee90cfbdb807c651c52ef0c1e6a123950f19f9a62aafd4d"
original_class_hash = "0x8229c3d9b1c3f36ee90cfbdb807c651c52ef0c1e6a123950f19f9a62aafd4d"
abi = "manifests/dev/abis/deployments/models/game_models_storage_battles_entityStorage_entity_storage.json"
name = "game::models::storage::battles::entityStorage::entity_storage"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "entityIndex"
type = "u32"
key = true

[[models.members]]
name = "entityVal"
type = "Entity"
key = false

[[models.members]]
name = "healthOnTurnProcCount"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4692b7a84ab642b1c01846ffd39d6af3fb9925df548f783fd95d8051807dfbb"
original_class_hash = "0x4692b7a84ab642b1c01846ffd39d6af3fb9925df548f783fd95d8051807dfbb"
abi = "manifests/dev/abis/deployments/models/game_models_storage_battles_healthOnTurnProcStorage_health_on_turn_proc_storage.json"
name = "game::models::storage::battles::healthOnTurnProcStorage::health_on_turn_proc_storage"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "entityIndex"
type = "u32"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "healthOnTurnProc"
type = "HealthOnTurnProc"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3f692130f8e66e32c447bddf5f92cbdc776de820e7782dce0f9ce2320362cfa"
original_class_hash = "0x3f692130f8e66e32c447bddf5f92cbdc776de820e7782dce0f9ce2320362cfa"
abi = "manifests/dev/abis/deployments/models/game_models_storage_battles_turnTimelineStorage_turn_timeline_storage.json"
name = "game::models::storage::battles::turnTimelineStorage::turn_timeline_storage"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "index"
type = "u16"
key = true

[[models.members]]
name = "entityIndex"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2b45c2aef761e36e37440ffe7cdcc3c3f462686ce701dd88a336fb694aaa4dc"
original_class_hash = "0x2b45c2aef761e36e37440ffe7cdcc3c3f462686ce701dd88a336fb694aaa4dc"
abi = "manifests/dev/abis/deployments/models/game_models_storage_level_levelEnemy_level_enemy.json"
name = "game::models::storage::level::levelEnemy::level_enemy"

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "level"
type = "u16"
key = true

[[models.members]]
name = "index"
type = "u16"
key = true

[[models.members]]
name = "hero"
type = "Hero"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x676d76cda9e635e05088a925ae2cbf6579706f9ff97d222aa426d9c3ff0d2e"
original_class_hash = "0x676d76cda9e635e05088a925ae2cbf6579706f9ff97d222aa426d9c3ff0d2e"
abi = "manifests/dev/abis/deployments/models/game_models_storage_level_levelInfos_level_infos.json"
name = "game::models::storage::level::levelInfos::level_infos"

[[models.members]]
name = "map"
type = "u16"
key = true

[[models.members]]
name = "level"
type = "u16"
key = true

[[models.members]]
name = "energyCost"
type = "u16"
key = false

[[models.members]]
name = "enemiesCount"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2efcc3bb0401b769915472a1a1b9eaeefd24dda440ad64fd60ca9b720eb7207"
original_class_hash = "0x2efcc3bb0401b769915472a1a1b9eaeefd24dda440ad64fd60ca9b720eb7207"
abi = "manifests/dev/abis/deployments/models/game_models_storage_skill_skillBuff_skill_buff.json"
name = "game::models::storage::skill::skillBuff::skill_buff"

[[models.members]]
name = "skillName"
type = "felt252"
key = true

[[models.members]]
name = "index"
type = "u16"
key = true

[[models.members]]
name = "buff"
type = "Buff"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2b195d45f9ce58172ca9b71b241456c26e583eff76f2d1a598b448bb16cd032"
original_class_hash = "0x2b195d45f9ce58172ca9b71b241456c26e583eff76f2d1a598b448bb16cd032"
abi = "manifests/dev/abis/deployments/models/game_models_storage_skill_skillInfos_skill_infos.json"
name = "game::models::storage::skill::skillInfos::skill_infos"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "cooldown"
type = "u8"
key = false

[[models.members]]
name = "damage"
type = "Damage"
key = false

[[models.members]]
name = "heal"
type = "Heal"
key = false

[[models.members]]
name = "targetType"
type = "TargetType"
key = false

[[models.members]]
name = "accuracy"
type = "u16"
key = false

[[models.members]]
name = "buffsCount"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x380ecd9e601bc5acf2591907c128f7ecb6d2942c28496a466dba004378e0262"
original_class_hash = "0x380ecd9e601bc5acf2591907c128f7ecb6d2942c28496a466dba004378e0262"
abi = "manifests/dev/abis/deployments/models/game_models_storage_skill_skillNameSet_skill_name_set.json"
name = "game::models::storage::skill::skillNameSet::skill_name_set"

[[models.members]]
name = "heroName"
type = "felt252"
key = true

[[models.members]]
name = "skill0"
type = "felt252"
key = false

[[models.members]]
name = "skill1"
type = "felt252"
key = false

[[models.members]]
name = "skill2"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x622a395be48de8cecdae34195bb20140b4f152e3bbd2523afde076bd193d5ef"
original_class_hash = "0x622a395be48de8cecdae34195bb20140b4f152e3bbd2523afde076bd193d5ef"
abi = "manifests/dev/abis/deployments/models/game_models_storage_statistics_baseStatistics_base_statistics.json"
name = "game::models::storage::statistics::baseStatistics::base_statistics"

[[models.members]]
name = "heroName"
type = "felt252"
key = true

[[models.members]]
name = "statistics"
type = "Statistics"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3b70a0cc3b8bb557a5050daba31c552e4a27e1654565561398475aef898febb"
original_class_hash = "0x3b70a0cc3b8bb557a5050daba31c552e4a27e1654565561398475aef898febb"
abi = "manifests/dev/abis/deployments/models/game_models_storage_statistics_bonusRuneStatistics_bonus_rune_statistics.json"
name = "game::models::storage::statistics::bonusRuneStatistics::bonus_rune_statistics"

[[models.members]]
name = "statistic"
type = "RuneStatistic"
key = true

[[models.members]]
name = "rarity"
type = "RuneRarity"
key = true

[[models.members]]
name = "isPercent"
type = "bool"
key = true

[[models.members]]
name = "value"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x591bcc83fb5ce1b9c702b3f0ff66bf8f54f7e9aaefbe70b3a6d8fbcbef32430"
original_class_hash = "0x591bcc83fb5ce1b9c702b3f0ff66bf8f54f7e9aaefbe70b3a6d8fbcbef32430"
abi = "manifests/dev/abis/deployments/models/game_models_storage_statistics_runeStatistics_rune_statistics.json"
name = "game::models::storage::statistics::runeStatistics::rune_statistics"

[[models.members]]
name = "statistic"
type = "RuneStatistic"
key = true

[[models.members]]
name = "rarity"
type = "RuneRarity"
key = true

[[models.members]]
name = "isPercent"
type = "bool"
key = true

[[models.members]]
name = "value"
type = "u32"
key = false
