kind = "DojoModel"
class_hash = "0x2efcc3bb0401b769915472a1a1b9eaeefd24dda440ad64fd60ca9b720eb7207"
original_class_hash = "0x2efcc3bb0401b769915472a1a1b9eaeefd24dda440ad64fd60ca9b720eb7207"
abi = "manifests/dev/abis/base/models/game_models_storage_skill_skillBuff_skill_buff.json"
name = "game::models::storage::skill::skillBuff::skill_buff"

[[members]]
name = "skillName"
type = "felt252"
key = true

[[members]]
name = "index"
type = "u16"
key = true

[[members]]
name = "buff"
type = "Buff"
key = false
