kind = "DojoModel"
class_hash = "0x200295409185bdfb3b82b476396eccfcfb959aa32416827957bc8a3e5aafb7c"
original_class_hash = "0x200295409185bdfb3b82b476396eccfcfb959aa32416827957bc8a3e5aafb7c"
abi = "manifests/dev/base/abis/models/game-HealthOnTurnProcStorage-6fad5dfd.json"
tag = "game-HealthOnTurnProcStorage"
manifest_name = "game-HealthOnTurnProcStorage-6fad5dfd"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "entityIndex"
type = "u32"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "healthOnTurnProc"
type = "HealthOnTurnProc"
key = false
