kind = "DojoModel"
class_hash = "0x591bcc83fb5ce1b9c702b3f0ff66bf8f54f7e9aaefbe70b3a6d8fbcbef32430"
original_class_hash = "0x591bcc83fb5ce1b9c702b3f0ff66bf8f54f7e9aaefbe70b3a6d8fbcbef32430"
abi = "manifests/dev/abis/base/models/game_models_storage_statistics_runeStatistics_rune_statistics.json"
name = "game::models::storage::statistics::runeStatistics::rune_statistics"

[[members]]
name = "statistic"
type = "RuneStatistic"
key = true

[[members]]
name = "rarity"
type = "RuneRarity"
key = true

[[members]]
name = "isPercent"
type = "bool"
key = true

[[members]]
name = "value"
type = "u32"
key = false
