kind = "DojoModel"
class_hash = "0x2c3f5999d32014291464f32b03b55d2925082e1716926436d9bc4c4e711e78d"
original_class_hash = "0x2c3f5999d32014291464f32b03b55d2925082e1716926436d9bc4c4e711e78d"
abi = "manifests/dev/base/abis/models/game-TurnTimelineStorage-64578faf.json"
tag = "game-TurnTimelineStorage"
qualified_path = "game::models::storage::battles::turnTimelineStorage::turn_timeline_storage"
manifest_name = "game-TurnTimelineStorage-64578faf"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "index"
type = "u16"
key = true

[[members]]
name = "entityIndex"
type = "u16"
key = false
