kind = "DojoModel"
class_hash = "0xc277e179f7840eb573bf7bb7722332a39abee1d7bcf77c50a76c1950b1f38d"
original_class_hash = "0xc277e179f7840eb573bf7bb7722332a39abee1d7bcf77c50a76c1950b1f38d"
abi = "manifests/dev/abis/base/models/game_models_account_runes_runes.json"
name = "game::models::account::runes::runes"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "rune"
type = "Rune"
key = false
