kind = "DojoModel"
class_hash = "0x73357dc71979b36dcfdf54709e478ad6f0f545d933c1d0c7c5bae24a5bc62e7"
original_class_hash = "0x73357dc71979b36dcfdf54709e478ad6f0f545d933c1d0c7c5bae24a5bc62e7"
abi = "manifests/dev/base/abis/models/game-EnemyRanges-28af3414.json"
tag = "game-EnemyRanges"
qualified_path = "game::models::storage::arena::enemyRanges::enemy_ranges"
manifest_name = "game-EnemyRanges-28af3414"

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "minRank"
type = "u64"
key = false

[[members]]
name = "range"
type = "u64"
key = false
