kind = "DojoModel"
class_hash = "0x53858f3361af749d8e5d8e4a5b0bde814a061c57a24846ab9a4afaea284010f"
original_class_hash = "0x53858f3361af749d8e5d8e4a5b0bde814a061c57a24846ab9a4afaea284010f"
abi = "manifests/dev/base/abis/models/game-SkillBuff-4cc3679b.json"
tag = "game-SkillBuff"
manifest_name = "game-SkillBuff-4cc3679b"

[[members]]
name = "skillName"
type = "felt252"
key = true

[[members]]
name = "index"
type = "u16"
key = true

[[members]]
name = "buff"
type = "Buff"
key = false
