kind = "DojoModel"
class_hash = "0x76f75ac2e7c0010fe59a56431805a6a12dc1c5bd97a016b022063ca8de4db6a"
original_class_hash = "0x76f75ac2e7c0010fe59a56431805a6a12dc1c5bd97a016b022063ca8de4db6a"
abi = "manifests/dev/base/abis/models/game-GlobalQuests-26e30eac.json"
tag = "game-GlobalQuests"
qualified_path = "game::models::storage::quest::globalQuests::global_quests"
manifest_name = "game-GlobalQuests-26e30eac"

[[members]]
name = "map"
type = "Map"
key = true

[[members]]
name = "mapProgressRequired"
type = "u16"
key = true

[[members]]
name = "rewardType"
type = "RewardType"
key = false

[[members]]
name = "rewardQuantity"
type = "u32"
key = false
