kind = "DojoModel"
class_hash = "0x29f228b120649be26c9d120e42f5c5b3399385406dd35bc67f6b00c8b9c9091"
original_class_hash = "0x29f228b120649be26c9d120e42f5c5b3399385406dd35bc67f6b00c8b9c9091"
abi = "manifests/dev/base/abis/models/game-SkillNameSet-578ae399.json"
tag = "game-SkillNameSet"
qualified_path = "game::models::storage::skill::skillNameSet::skill_name_set"
manifest_name = "game-SkillNameSet-578ae399"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "skill"
type = "felt252"
key = false
