kind = "DojoModel"
class_hash = "0x2b195d45f9ce58172ca9b71b241456c26e583eff76f2d1a598b448bb16cd032"
original_class_hash = "0x2b195d45f9ce58172ca9b71b241456c26e583eff76f2d1a598b448bb16cd032"
abi = "manifests/dev/abis/base/models/game_models_storage_skill_skillInfos_skill_infos.json"
name = "game::models::storage::skill::skillInfos::skill_infos"

[[members]]
name = "name"
type = "felt252"
key = true

[[members]]
name = "cooldown"
type = "u8"
key = false

[[members]]
name = "damage"
type = "Damage"
key = false

[[members]]
name = "heal"
type = "Heal"
key = false

[[members]]
name = "targetType"
type = "TargetType"
key = false

[[members]]
name = "accuracy"
type = "u16"
key = false

[[members]]
name = "buffsCount"
type = "u16"
key = false
