kind = "DojoModel"
class_hash = "0xa97d1550b23466c50e2cabcad1523afa55d84baaf0ec1ff9624ea82da59f90"
original_class_hash = "0xa97d1550b23466c50e2cabcad1523afa55d84baaf0ec1ff9624ea82da59f90"
abi = "manifests/dev/base/abis/models/game-TurnTimelineStorage-64578faf.json"
tag = "game-TurnTimelineStorage"
manifest_name = "game-TurnTimelineStorage-64578faf"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "index"
type = "u16"
key = true

[[members]]
name = "entityIndex"
type = "u16"
key = false
