kind = "DojoModel"
class_hash = "0x51bc67fda49e4e7aab419185051834e1d42a01bc9bf76ddda154d4f9a8ebf24"
original_class_hash = "0x51bc67fda49e4e7aab419185051834e1d42a01bc9bf76ddda154d4f9a8ebf24"
abi = "manifests/dev/abis/base/models/game_models_storage_arena_arenaTeams_arena_team.json"
name = "game::models::storage::arena::arenaTeams::arena_team"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "heroIndex"
type = "u32"
key = false
