kind = "DojoModel"
class_hash = "0xfe77c6cf0de023a542df66ce7ff4c0a72e8c00f4ec7c666538543135c4a5e"
original_class_hash = "0xfe77c6cf0de023a542df66ce7ff4c0a72e8c00f4ec7c666538543135c4a5e"
abi = "manifests/dev/base/abis/models/game-Usernames-6fb02379.json"
tag = "game-Usernames"
qualified_path = "game::models::storage::usernames::usernames"
manifest_name = "game-Usernames-6fb02379"

[[members]]
name = "username"
type = "felt252"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false
