kind = "DojoModel"
class_hash = "0x8229c3d9b1c3f36ee90cfbdb807c651c52ef0c1e6a123950f19f9a62aafd4d"
original_class_hash = "0x8229c3d9b1c3f36ee90cfbdb807c651c52ef0c1e6a123950f19f9a62aafd4d"
abi = "manifests/dev/abis/base/models/game_models_storage_battles_entityStorage_entity_storage.json"
name = "game::models::storage::battles::entityStorage::entity_storage"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "entityIndex"
type = "u32"
key = true

[[members]]
name = "entityVal"
type = "Entity"
key = false

[[members]]
name = "healthOnTurnProcCount"
type = "u32"
key = false
