kind = "DojoModel"
class_hash = "0x567d5a971d197938d14e554a5ed265d4a4c6ffcb08ebd1decf8f18764430110"
original_class_hash = "0x567d5a971d197938d14e554a5ed265d4a4c6ffcb08ebd1decf8f18764430110"
abi = "manifests/dev/abis/base/models/game_models_storage_skill_skillNameSet_skill_name_set.json"
name = "game::models::storage::skill::skillNameSet::skill_name_set"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "skill"
type = "felt252"
key = false
