kind = "DojoModel"
class_hash = "0x708bfcebe814f943681f1353e0d8625fac2fb8a4c85916cbbe98dec694689bd"
original_class_hash = "0x708bfcebe814f943681f1353e0d8625fac2fb8a4c85916cbbe98dec694689bd"
abi = "manifests/dev/abis/base/models/game_models_account_account.json"
name = "game::models::account::account"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "username"
type = "felt252"
key = false

[[members]]
name = "energy"
type = "u16"
key = false

[[members]]
name = "pvpEnergy"
type = "u16"
key = false

[[members]]
name = "crystals"
type = "u32"
key = false

[[members]]
name = "gems"
type = "u32"
key = false

[[members]]
name = "lastEnergyUpdateTimestamp"
type = "u64"
key = false

[[members]]
name = "lastPvpEnergyUpdateTimestamp"
type = "u64"
key = false

[[members]]
name = "runesCount"
type = "u32"
key = false

[[members]]
name = "heroesCount"
type = "u32"
key = false
