kind = "DojoModel"
class_hash = "0x328dfd8578e02faf5d7a0cdb27155070e6a9b6a5c953171d1b1371f58fbce26"
original_class_hash = "0x328dfd8578e02faf5d7a0cdb27155070e6a9b6a5c953171d1b1371f58fbce26"
abi = "manifests/dev/abis/base/models/game_models_storage_battles_battleStorage_battle_storage.json"
name = "game::models::storage::battles::battleStorage::battle_storage"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "level"
type = "u16"
key = false

[[members]]
name = "entitiesCount"
type = "u32"
key = false

[[members]]
name = "aliveEntitiesCount"
type = "u32"
key = false

[[members]]
name = "isBattleOver"
type = "bool"
key = false

[[members]]
name = "isWaitingForPlayerAction"
type = "bool"
key = false
