kind = "DojoModel"
class_hash = "0x15205dc9df776e52e06082fc0738ced681aafa8c5bf77f821f54e5c033533a8"
original_class_hash = "0x15205dc9df776e52e06082fc0738ced681aafa8c5bf77f821f54e5c033533a8"
abi = "manifests/dev/base/abis/models/game-BaseHero-17593f72.json"
tag = "game-BaseHero"
qualified_path = "game::models::storage::baseHero::base_hero"
manifest_name = "game-BaseHero-17593f72"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "statistics"
type = "Statistics"
key = false

[[members]]
name = "skillsCount"
type = "u8"
key = false
