kind = "DojoModel"
class_hash = "0x224c5a1b4956fcec1bf44b7916d0d09ace009d918964e6c319e50d2169214a5"
original_class_hash = "0x224c5a1b4956fcec1bf44b7916d0d09ace009d918964e6c319e50d2169214a5"
abi = "manifests/dev/base/abis/models/game-LevelInfos-305d29c6.json"
tag = "game-LevelInfos"
qualified_path = "game::models::storage::level::levelInfos::level_infos"
manifest_name = "game-LevelInfos-305d29c6"

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "level"
type = "u16"
key = true

[[members]]
name = "energyCost"
type = "u16"
key = false

[[members]]
name = "enemiesCount"
type = "u16"
key = false
