kind = "DojoModel"
class_hash = "0x3335c9d2e97663677d5852d4f4922fd933166938b229791c2a1f34288921490"
original_class_hash = "0x3335c9d2e97663677d5852d4f4922fd933166938b229791c2a1f34288921490"
abi = "manifests/dev/base/abis/models/game-BaseHero-17593f72.json"
tag = "game-BaseHero"
manifest_name = "game-BaseHero-17593f72"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "statistics"
type = "Statistics"
key = false

[[members]]
name = "skillsCount"
type = "u8"
key = false
