kind = "DojoModel"
class_hash = "0x6c871d2fa7ecf1aaf13738d051a9477b4729cb47027df1cf57c6c171624ccfb"
original_class_hash = "0x6c871d2fa7ecf1aaf13738d051a9477b4729cb47027df1cf57c6c171624ccfb"
abi = "manifests/dev/abis/base/models/game_models_storage_baseHero_base_hero.json"
name = "game::models::storage::baseHero::base_hero"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "statistics"
type = "Statistics"
key = false

[[members]]
name = "skillsCount"
type = "u8"
key = false
