kind = "DojoModel"
class_hash = "0xd265ef2a0c455c1a5af9dd6d337d88bb9be8723b3a280d55cc7014a522af84"
original_class_hash = "0xd265ef2a0c455c1a5af9dd6d337d88bb9be8723b3a280d55cc7014a522af84"
abi = "manifests/dev/base/abis/models/game-Heroes-3404b465.json"
tag = "game-Heroes"
manifest_name = "game-Heroes-3404b465"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "hero"
type = "Hero"
key = false
