kind = "DojoModel"
class_hash = "0x288c026dbb92eb9d3351ca2f8b4973c728c7a3777e9a6bc46424e29c5941805"
original_class_hash = "0x288c026dbb92eb9d3351ca2f8b4973c728c7a3777e9a6bc46424e29c5941805"
abi = "manifests/dev/base/abis/models/game-Account-29dd3dd7.json"
tag = "game-Account"
qualified_path = "game::models::account::account"
manifest_name = "game-Account-29dd3dd7"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "username"
type = "felt252"
key = false

[[members]]
name = "energy"
type = "u16"
key = false

[[members]]
name = "pvpEnergy"
type = "u16"
key = false

[[members]]
name = "crystals"
type = "u32"
key = false

[[members]]
name = "gems"
type = "u32"
key = false

[[members]]
name = "lastEnergyUpdateTimestamp"
type = "u64"
key = false

[[members]]
name = "lastPvpEnergyUpdateTimestamp"
type = "u64"
key = false

[[members]]
name = "runesCount"
type = "u32"
key = false

[[members]]
name = "heroesCount"
type = "u32"
key = false

[[members]]
name = "summonChests"
type = "u32"
key = false
