kind = "DojoModel"
class_hash = "0x4de3376b236b4f775c4f26541befd8c8a615794d12d94cffe22f4b8ab56c3ef"
original_class_hash = "0x4de3376b236b4f775c4f26541befd8c8a615794d12d94cffe22f4b8ab56c3ef"
abi = "manifests/dev/abis/base/models/game_models_account_heroes_heroes.json"
name = "game::models::account::heroes::heroes"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "hero"
type = "Hero"
key = false
