kind = "DojoModel"
class_hash = "0x676d76cda9e635e05088a925ae2cbf6579706f9ff97d222aa426d9c3ff0d2e"
original_class_hash = "0x676d76cda9e635e05088a925ae2cbf6579706f9ff97d222aa426d9c3ff0d2e"
abi = "manifests/dev/abis/base/models/game_models_storage_level_levelInfos_level_infos.json"
name = "game::models::storage::level::levelInfos::level_infos"

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "level"
type = "u16"
key = true

[[members]]
name = "energyCost"
type = "u16"
key = false

[[members]]
name = "enemiesCount"
type = "u16"
key = false
