kind = "DojoModel"
class_hash = "0x4c7f5da1fc1c6aec2f2a112a4ba56170142889b2f006b90168224936b50bcfc"
original_class_hash = "0x4c7f5da1fc1c6aec2f2a112a4ba56170142889b2f006b90168224936b50bcfc"
abi = "manifests/dev/base/abis/models/game-MapProgress-1bbf0d3a.json"
tag = "game-MapProgress"
qualified_path = "game::models::storage::mapProgress::map_progress"
manifest_name = "game-MapProgress-1bbf0d3a"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "level"
type = "u16"
key = false
