kind = "DojoModel"
class_hash = "0x776a006bc59c8c05d915a3688495cc00852e752b52e403d9802d1a84ddc5f5e"
original_class_hash = "0x776a006bc59c8c05d915a3688495cc00852e752b52e403d9802d1a84ddc5f5e"
abi = "manifests/dev/base/abis/models/game-ArenaConfig-55fabecf.json"
tag = "game-ArenaConfig"
qualified_path = "game::models::storage::arena::arenaConfig::arena_config"
manifest_name = "game-ArenaConfig-55fabecf"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "enemyRangesByRankLength"
type = "u32"
key = false

[[members]]
name = "gemsRewardsLength"
type = "u32"
key = false
