kind = "DojoModel"
class_hash = "0x3b70a0cc3b8bb557a5050daba31c552e4a27e1654565561398475aef898febb"
original_class_hash = "0x3b70a0cc3b8bb557a5050daba31c552e4a27e1654565561398475aef898febb"
abi = "manifests/dev/abis/base/models/game_models_storage_statistics_bonusRuneStatistics_bonus_rune_statistics.json"
name = "game::models::storage::statistics::bonusRuneStatistics::bonus_rune_statistics"

[[members]]
name = "statistic"
type = "RuneStatistic"
key = true

[[members]]
name = "rarity"
type = "RuneRarity"
key = true

[[members]]
name = "isPercent"
type = "bool"
key = true

[[members]]
name = "value"
type = "u32"
key = false
