kind = "DojoModel"
class_hash = "0x42451b80683f8654453cd3774ccefeab261ddc905ddf7fd05d1fd4dd9521a0"
original_class_hash = "0x42451b80683f8654453cd3774ccefeab261ddc905ddf7fd05d1fd4dd9521a0"
abi = "manifests/dev/abis/base/models/game_models_storage_battles_arenaBattleStorage_arena_battle_storage.json"
name = "game::models::storage::battles::arenaBattleStorage::arena_battle_storage"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "enemyOwner"
type = "ContractAddress"
key = false
