kind = "DojoModel"
class_hash = "0x41ed76294d945c236a5e9563a66fc865153dde18cd43c1686aac0c88c2f06bf"
original_class_hash = "0x41ed76294d945c236a5e9563a66fc865153dde18cd43c1686aac0c88c2f06bf"
abi = "manifests/dev/base/abis/models/game-AccountQuests-28c6c5cc.json"
tag = "game-AccountQuests"
qualified_path = "game::models::storage::quest::accountQuests::account_quests"
manifest_name = "game-AccountQuests-28c6c5cc"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "mapProgressRequired"
type = "u16"
key = true

[[members]]
name = "hasClaimedRewards"
type = "bool"
key = false
