kind = "DojoModel"
class_hash = "0x4692b7a84ab642b1c01846ffd39d6af3fb9925df548f783fd95d8051807dfbb"
original_class_hash = "0x4692b7a84ab642b1c01846ffd39d6af3fb9925df548f783fd95d8051807dfbb"
abi = "manifests/dev/abis/base/models/game_models_storage_battles_healthOnTurnProcStorage_health_on_turn_proc_storage.json"
name = "game::models::storage::battles::healthOnTurnProcStorage::health_on_turn_proc_storage"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "entityIndex"
type = "u32"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "healthOnTurnProc"
type = "HealthOnTurnProc"
key = false
