kind = "DojoModel"
class_hash = "0x380ecd9e601bc5acf2591907c128f7ecb6d2942c28496a466dba004378e0262"
original_class_hash = "0x380ecd9e601bc5acf2591907c128f7ecb6d2942c28496a466dba004378e0262"
abi = "manifests/dev/abis/base/models/game_models_storage_skill_skillNameSet_skill_name_set.json"
name = "game::models::storage::skill::skillNameSet::skill_name_set"

[[members]]
name = "heroName"
type = "felt252"
key = true

[[members]]
name = "skill0"
type = "felt252"
key = false

[[members]]
name = "skill1"
type = "felt252"
key = false

[[members]]
name = "skill2"
type = "felt252"
key = false
