kind = "DojoModel"
class_hash = "0x11e210352255a78c18e716d0ba63623dfee294dabd0d01b7f684dd80810da5d"
original_class_hash = "0x11e210352255a78c18e716d0ba63623dfee294dabd0d01b7f684dd80810da5d"
abi = "manifests/dev/abis/base/models/game_models_storage_arena_enemyRanges_enemy_ranges.json"
name = "game::models::storage::arena::enemyRanges::enemy_ranges"

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "minRank"
type = "u64"
key = false

[[members]]
name = "range"
type = "u64"
key = false
