kind = "DojoModel"
class_hash = "0x494f8e15440ec90fbf52f80800e0d750ec57dc6c0197adbec739767d821aa3"
original_class_hash = "0x494f8e15440ec90fbf52f80800e0d750ec57dc6c0197adbec739767d821aa3"
abi = "manifests/dev/base/abis/models/game-GlobalQuests-26e30eac.json"
tag = "game-GlobalQuests"
qualified_path = "game::models::storage::quest::globalQuests::global_quests"
manifest_name = "game-GlobalQuests-26e30eac"

[[members]]
name = "map"
type = "u16"
key = true

[[members]]
name = "mapProgressRequired"
type = "u16"
key = true

[[members]]
name = "rewardType"
type = "RewardType"
key = false

[[members]]
name = "rewardQuantity"
type = "u32"
key = false
