kind = "DojoContract"
class_hash = "0x2260f0cea6bcdbe3f7bfe84be063533b3d908fcd195d25aa510e421d2524223"
original_class_hash = "0x2260f0cea6bcdbe3f7bfe84be063533b3d908fcd195d25aa510e421d2524223"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_game_Game.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "game::systems::game::Game"
