kind = "DojoContract"
class_hash = "0x742ba0141fe4cdf99ccd2f53f45f2db3e1101e239feb705243fd66b4e2c5360"
original_class_hash = "0x742ba0141fe4cdf99ccd2f53f45f2db3e1101e239feb705243fd66b4e2c5360"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_game_Game.json"
reads = []
writes = []
computed = []
name = "game::systems::game::Game"
