kind = "DojoContract"
class_hash = "0x367072867c3c9c2295d4d26bc2e8be39a3d32d7fbe45c83b91c12a66f1830f3"
original_class_hash = "0x367072867c3c9c2295d4d26bc2e8be39a3d32d7fbe45c83b91c12a66f1830f3"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_settings_Settings.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "game::systems::settings::Settings"
