kind = "DojoContract"
class_hash = "0x53ad04e1465f0e5841d445c6bdf05363413073c9868036f68c171755ef6bbba"
original_class_hash = "0x53ad04e1465f0e5841d445c6bdf05363413073c9868036f68c171755ef6bbba"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_entityFactory_EntityFactory.json"
reads = []
writes = []
computed = []
name = "game::systems::entityFactory::EntityFactory"
