kind = "DojoContract"
class_hash = "0x399df5d89c3a2249a574fef728fa4870f45433ef82ab538b93578719fcbfde6"
original_class_hash = "0x399df5d89c3a2249a574fef728fa4870f45433ef82ab538b93578719fcbfde6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game-Settings-4d1bc91c.json"
reads = []
writes = []
init_calldata = []
tag = "game-Settings"
systems = []
manifest_name = "game-Settings-4d1bc91c"
