kind = "DojoContract"
class_hash = "0x493539a53030c4911c5437b311ad9e120bbf5123dd0b70be446c52ffda47212"
original_class_hash = "0x493539a53030c4911c5437b311ad9e120bbf5123dd0b70be446c52ffda47212"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game-Settings-4d1bc91c.json"
reads = []
writes = []
init_calldata = []
tag = "game-Settings"
systems = []
manifest_name = "game-Settings-4d1bc91c"
