kind = "DojoContract"
class_hash = "0x3b68e46ce1dd930ae0f21e52f98547ca7b8615264418d088b1087a5209880b1"
original_class_hash = "0x3b68e46ce1dd930ae0f21e52f98547ca7b8615264418d088b1087a5209880b1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_entityFactory_EntityFactory.json"
reads = []
writes = []
computed = []
name = "game::systems::entityFactory::EntityFactory"
