kind = "DojoContract"
class_hash = "0x32c028f74ab7ce7d28eab5f25e776f2d4a2e351e7b171bb6490d23b69ac54db"
original_class_hash = "0x32c028f74ab7ce7d28eab5f25e776f2d4a2e351e7b171bb6490d23b69ac54db"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/game_systems_game_Game.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "game::systems::game::Game"
