kind = "DojoContract"
class_hash = "0x3b982b2c063396c15862aab255358302cd42eee79f919e4c3693b0e3a593047"
original_class_hash = "0x3b982b2c063396c15862aab255358302cd42eee79f919e4c3693b0e3a593047"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game-Game-1a8648a1.json"
reads = []
writes = []
init_calldata = []
tag = "game-Game"
systems = [
    "startPvpBattle",
    "playArenaTurn",
    "startBattle",
    "playTurn",
    "initPvp",
    "setPvpTeam",
    "equipRune",
    "unequipRune",
    "upgradeRune",
    "mintHero",
    "mintRune",
    "createAccount",
]
manifest_name = "game-Game-1a8648a1"
