kind = "DojoContract"
class_hash = "0xf0438ad1d5be74813591369fe0606b60690c35269284e19e67f6afc464c0a4"
original_class_hash = "0xf0438ad1d5be74813591369fe0606b60690c35269284e19e67f6afc464c0a4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game-Settings-4d1bc91c.json"
reads = []
writes = []
init_calldata = []
tag = "game-Settings"
systems = []
manifest_name = "game-Settings-4d1bc91c"
