kind = "DojoContract"
class_hash = "0x77f65fd8c22e6db379d823f26eea07eec6413c7bec2884f5b4b7410b75cab91"
original_class_hash = "0x77f65fd8c22e6db379d823f26eea07eec6413c7bec2884f5b4b7410b75cab91"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game-Settings-4d1bc91c.json"
reads = []
writes = []
init_calldata = []
tag = "game-Settings"
systems = []
manifest_name = "game-Settings-4d1bc91c"
